#1771 | Retry prod bundle creation if it fails

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -403,7 +403,22 @@ jobs:
             ./gradlew --stop || true
             sleep 10
             echo "Gradle daemon stopped after patch, CPU/memory relieved"
-      - run: versionName=<< pipeline.parameters.versionName >> versionCode=<< pipeline.parameters.versionCode >> make bundle_release_prod_without_clean
+#      - run: versionName=<< pipeline.parameters.versionName >> versionCode=<< pipeline.parameters.versionCode >> make bundle_release_prod_without_clean
+      - run:
+          name: Create Prod bundle with retry
+          command: |
+            n=0
+            until [ "$n" -ge 3 ]
+            do
+               versionName=<< pipeline.parameters.versionName >> versionCode=<< pipeline.parameters.versionCode >> make bundle_release_prod_without_clean && break
+               n=$((n+1)) 
+               echo "Command failed. Attempt $n/3. Retrying in 10 seconds..."
+               sleep 10
+            done
+            if [ "$n" -eq 3 ]; then
+               echo "Command failed after 3 attempts"
+               exit 1
+            fi
       - store_artifacts:
           path: packages/openchs-android/android/app/build/outputs/bundle/<< pipeline.parameters.flavor >>Release/app-<< pipeline.parameters.flavor >>-release.aab
           destination: << pipeline.parameters.flavor >>-live-<< pipeline.parameters.versionName >>-<< pipeline.git.revision >>.aab
